substitutions:
  name: sk60
  device_description: "Monitor and control a SK60"
  tx_pin: D3
  rx_pin: D4

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-dps"
    version: 1.4.0

esp8266:
  board: d1_mini

external_components:
  - source: ./components
    refresh: 0s

wifi:
  ssid: kmmh1
  password: lexydexy1915

ota:
  platform: esphome

logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
      key: "GMvBL0LS8AVrUB8fsJ0iqKZUxlb21wJJARM8CV3tqfs="

uart:
  id: uart_0
  baud_rate: 115200
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug: 
     direction: BOTH



modbus:
  id: modbus0
  uart_id: uart_0
  send_wait_time: 0ms

xysk:
  id: xysk0
  modbus_id: modbus0
  update_interval: 10s
  current_resolution: AUTO

binary_sensor:
  - platform: xysk
    output:
      name: "${name} output"
    key_lock:
      name: "${name} key lock"
    constant_current_mode:
      name: "${name} constant current mode"

sensor:
  - platform: xysk
    output_voltage:
      name: "${name} output voltage"
    output_current:
      name: "${name} output current"
    output_power:
      name: "${name} output power"
    input_voltage:
      name: "${name} input voltage"
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"
    backlight_brightness:
      name: "${name} backlight brightness"
    firmware_version:
      name: "${name} firmware version"
    internal_temperature:
      name: "${name} internal temperature"

text_sensor:
  - platform: xysk
    protection_status:
      name: "${name} protection status"
    device_model:
      name: "${name} device model"

switch:
  - platform: xysk
    output:
      name: "${name} output"
    key_lock:
      name: "${name} key lock"

number:
  - platform: xysk
    voltage_setting:
      name: "${name} voltage setting"
    current_setting:
      name: "${name} current setting"